from fastapi import APIRouter
from app.schemas.prediction import PredictionRequest, PredictionResponse
from pathlib import Path
import pickle

import pandas as pd

router = APIRouter()

MODEL_PATH = Path("app/ml/model.pkl")

with MODEL_PATH.open("rb") as f:
    model = pickle.load(f)

@router.post("/predict", response_model=PredictionResponse)
def predict(payload: PredictionRequest) -> PredictionResponse:
    input_df = pd.DataFrame([
        {
            "age": payload.age,
            "bmi": payload.bmi,
            "smoker": "yes" if payload.smoker else "no",
            "region": payload.region,
            "children": payload.children
        }
    ])

    score = float(model.predict(input_df)[0])

    if score >= 0.7:
        level = "high"
    elif score >= 0.4:
        level = "medium"
    else:
        level = "low"

    return PredictionResponse(
        risk_score=round(score, 2),
        risk_level=level,
        explanation="Prediction generated by the trained sklearn model."
    )